/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddressAddDTO
 */
export interface AddressAddDTO {
    /**
     * 
     * @type {string}
     * @memberof AddressAddDTO
     */
    city?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressAddDTO
     */
    street?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AddressAddDTO
     */
    sNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof AddressAddDTO
     */
    scara?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AddressAddDTO
     */
    bloc?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AddressAddDTO
     */
    apartament?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AddressAddDTO
     */
    description?: string | null;
}

/**
 * Check if a given object implements the AddressAddDTO interface.
 */
export function instanceOfAddressAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddressAddDTOFromJSON(json: any): AddressAddDTO {
    return AddressAddDTOFromJSONTyped(json, false);
}

export function AddressAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'city': !exists(json, 'city') ? undefined : json['city'],
        'street': !exists(json, 'street') ? undefined : json['street'],
        'sNumber': !exists(json, 'sNumber') ? undefined : json['sNumber'],
        'scara': !exists(json, 'scara') ? undefined : json['scara'],
        'bloc': !exists(json, 'bloc') ? undefined : json['bloc'],
        'apartament': !exists(json, 'apartament') ? undefined : json['apartament'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function AddressAddDTOToJSON(value?: AddressAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'city': value.city,
        'street': value.street,
        'sNumber': value.sNumber,
        'scara': value.scara,
        'bloc': value.bloc,
        'apartament': value.apartament,
        'description': value.description,
    };
}

