/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddressDTO
 */
export interface AddressDTO {
    /**
     * 
     * @type {string}
     * @memberof AddressDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDTO
     */
    city?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressDTO
     */
    street?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AddressDTO
     */
    sNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof AddressDTO
     */
    scara?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AddressDTO
     */
    bloc?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AddressDTO
     */
    apartament?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AddressDTO
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddressDTO
     */
    userId?: string;
}

/**
 * Check if a given object implements the AddressDTO interface.
 */
export function instanceOfAddressDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddressDTOFromJSON(json: any): AddressDTO {
    return AddressDTOFromJSONTyped(json, false);
}

export function AddressDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'city': !exists(json, 'city') ? undefined : json['city'],
        'street': !exists(json, 'street') ? undefined : json['street'],
        'sNumber': !exists(json, 'sNumber') ? undefined : json['sNumber'],
        'scara': !exists(json, 'scara') ? undefined : json['scara'],
        'bloc': !exists(json, 'bloc') ? undefined : json['bloc'],
        'apartament': !exists(json, 'apartament') ? undefined : json['apartament'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
    };
}

export function AddressDTOToJSON(value?: AddressDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'city': value.city,
        'street': value.street,
        'sNumber': value.sNumber,
        'scara': value.scara,
        'bloc': value.bloc,
        'apartament': value.apartament,
        'description': value.description,
        'userId': value.userId,
    };
}

