/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CartDTO } from './CartDTO';
import {
    CartDTOFromJSON,
    CartDTOFromJSONTyped,
    CartDTOToJSON,
} from './CartDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface CartDTORequestResponse
 */
export interface CartDTORequestResponse {
    /**
     * 
     * @type {CartDTO}
     * @memberof CartDTORequestResponse
     */
    response?: CartDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof CartDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the CartDTORequestResponse interface.
 */
export function instanceOfCartDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CartDTORequestResponseFromJSON(json: any): CartDTORequestResponse {
    return CartDTORequestResponseFromJSONTyped(json, false);
}

export function CartDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : CartDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function CartDTORequestResponseToJSON(value?: CartDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': CartDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

