/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FacturiStateEnum } from './FacturiStateEnum';
import {
    FacturiStateEnumFromJSON,
    FacturiStateEnumFromJSONTyped,
    FacturiStateEnumToJSON,
} from './FacturiStateEnum';

/**
 * 
 * @export
 * @interface FacturiUpdateDTO
 */
export interface FacturiUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof FacturiUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof FacturiUpdateDTO
     */
    shippingTime?: Date | null;
    /**
     * 
     * @type {FacturiStateEnum}
     * @memberof FacturiUpdateDTO
     */
    state?: FacturiStateEnum;
}

/**
 * Check if a given object implements the FacturiUpdateDTO interface.
 */
export function instanceOfFacturiUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FacturiUpdateDTOFromJSON(json: any): FacturiUpdateDTO {
    return FacturiUpdateDTOFromJSONTyped(json, false);
}

export function FacturiUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FacturiUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'shippingTime': !exists(json, 'shippingTime') ? undefined : (json['shippingTime'] === null ? null : new Date(json['shippingTime'])),
        'state': !exists(json, 'state') ? undefined : FacturiStateEnumFromJSON(json['state']),
    };
}

export function FacturiUpdateDTOToJSON(value?: FacturiUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'shippingTime': value.shippingTime === undefined ? undefined : (value.shippingTime === null ? null : value.shippingTime.toISOString()),
        'state': FacturiStateEnumToJSON(value.state),
    };
}

