/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FacturiAddDTO
 */
export interface FacturiAddDTO {
    /**
     * 
     * @type {string}
     * @memberof FacturiAddDTO
     */
    idAdd?: string;
    /**
     * 
     * @type {string}
     * @memberof FacturiAddDTO
     */
    cartId?: string;
    /**
     * 
     * @type {string}
     * @memberof FacturiAddDTO
     */
    userId?: string;
}

/**
 * Check if a given object implements the FacturiAddDTO interface.
 */
export function instanceOfFacturiAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FacturiAddDTOFromJSON(json: any): FacturiAddDTO {
    return FacturiAddDTOFromJSONTyped(json, false);
}

export function FacturiAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FacturiAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'idAdd': !exists(json, 'idAdd') ? undefined : json['idAdd'],
        'cartId': !exists(json, 'cartId') ? undefined : json['cartId'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
    };
}

export function FacturiAddDTOToJSON(value?: FacturiAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'idAdd': value.idAdd,
        'cartId': value.cartId,
        'userId': value.userId,
    };
}

