/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FacturiStateEnum = {
    Processing: 'Processing',
    InTranzit: 'InTranzit',
    Arrived: 'Arrived',
    Cancelled: 'Cancelled'
} as const;
export type FacturiStateEnum = typeof FacturiStateEnum[keyof typeof FacturiStateEnum];


export function FacturiStateEnumFromJSON(json: any): FacturiStateEnum {
    return FacturiStateEnumFromJSONTyped(json, false);
}

export function FacturiStateEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): FacturiStateEnum {
    return json as FacturiStateEnum;
}

export function FacturiStateEnumToJSON(value?: FacturiStateEnum | null): any {
    return value as any;
}

