/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { FacturiDTOPagedResponse } from './FacturiDTOPagedResponse';
import {
    FacturiDTOPagedResponseFromJSON,
    FacturiDTOPagedResponseFromJSONTyped,
    FacturiDTOPagedResponseToJSON,
} from './FacturiDTOPagedResponse';

/**
 * 
 * @export
 * @interface FacturiDTOPagedResponseRequestResponse
 */
export interface FacturiDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {FacturiDTOPagedResponse}
     * @memberof FacturiDTOPagedResponseRequestResponse
     */
    response?: FacturiDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof FacturiDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the FacturiDTOPagedResponseRequestResponse interface.
 */
export function instanceOfFacturiDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FacturiDTOPagedResponseRequestResponseFromJSON(json: any): FacturiDTOPagedResponseRequestResponse {
    return FacturiDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function FacturiDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FacturiDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : FacturiDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function FacturiDTOPagedResponseRequestResponseToJSON(value?: FacturiDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': FacturiDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

