/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FacturiStateEnum } from './FacturiStateEnum';
import {
    FacturiStateEnumFromJSON,
    FacturiStateEnumFromJSONTyped,
    FacturiStateEnumToJSON,
} from './FacturiStateEnum';

/**
 * 
 * @export
 * @interface FacturiDTO
 */
export interface FacturiDTO {
    /**
     * 
     * @type {string}
     * @memberof FacturiDTO
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof FacturiDTO
     */
    pret?: number;
    /**
     * 
     * @type {Date}
     * @memberof FacturiDTO
     */
    shippingTime?: Date;
    /**
     * 
     * @type {FacturiStateEnum}
     * @memberof FacturiDTO
     */
    state?: FacturiStateEnum;
    /**
     * 
     * @type {string}
     * @memberof FacturiDTO
     */
    idAdd?: string;
    /**
     * 
     * @type {string}
     * @memberof FacturiDTO
     */
    cartId?: string;
    /**
     * 
     * @type {string}
     * @memberof FacturiDTO
     */
    userId?: string;
    /**
     * 
     * @type {Date}
     * @memberof FacturiDTO
     */
    date?: Date;
}

/**
 * Check if a given object implements the FacturiDTO interface.
 */
export function instanceOfFacturiDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FacturiDTOFromJSON(json: any): FacturiDTO {
    return FacturiDTOFromJSONTyped(json, false);
}

export function FacturiDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FacturiDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'pret': !exists(json, 'pret') ? undefined : json['pret'],
        'shippingTime': !exists(json, 'shippingTime') ? undefined : (new Date(json['shippingTime'])),
        'state': !exists(json, 'state') ? undefined : FacturiStateEnumFromJSON(json['state']),
        'idAdd': !exists(json, 'idAdd') ? undefined : json['idAdd'],
        'cartId': !exists(json, 'cartId') ? undefined : json['cartId'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'date': !exists(json, 'date') ? undefined : (new Date(json['date'])),
    };
}

export function FacturiDTOToJSON(value?: FacturiDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'pret': value.pret,
        'shippingTime': value.shippingTime === undefined ? undefined : (value.shippingTime.toISOString()),
        'state': FacturiStateEnumToJSON(value.state),
        'idAdd': value.idAdd,
        'cartId': value.cartId,
        'userId': value.userId,
        'date': value.date === undefined ? undefined : (value.date.toISOString()),
    };
}

