/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { FacturiDTO } from './FacturiDTO';
import {
    FacturiDTOFromJSON,
    FacturiDTOFromJSONTyped,
    FacturiDTOToJSON,
} from './FacturiDTO';

/**
 * 
 * @export
 * @interface FacturiDTORequestResponse
 */
export interface FacturiDTORequestResponse {
    /**
     * 
     * @type {FacturiDTO}
     * @memberof FacturiDTORequestResponse
     */
    response?: FacturiDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof FacturiDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the FacturiDTORequestResponse interface.
 */
export function instanceOfFacturiDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FacturiDTORequestResponseFromJSON(json: any): FacturiDTORequestResponse {
    return FacturiDTORequestResponseFromJSONTyped(json, false);
}

export function FacturiDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FacturiDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : FacturiDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function FacturiDTORequestResponseToJSON(value?: FacturiDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': FacturiDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

