/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FeedbackEnum = {
    Unsatisfactory: 'Unsatisfactory',
    Satisfactory: 'Satisfactory',
    Decent: 'Decent',
    NearPerfect: 'Near_Perfect'
} as const;
export type FeedbackEnum = typeof FeedbackEnum[keyof typeof FeedbackEnum];


export function FeedbackEnumFromJSON(json: any): FeedbackEnum {
    return FeedbackEnumFromJSONTyped(json, false);
}

export function FeedbackEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackEnum {
    return json as FeedbackEnum;
}

export function FeedbackEnumToJSON(value?: FeedbackEnum | null): any {
    return value as any;
}

