/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemUpdateDTO
 */
export interface ItemUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof ItemUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ItemUpdateDTO
     */
    producer?: string;
    /**
     * 
     * @type {string}
     * @memberof ItemUpdateDTO
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ItemUpdateDTO
     */
    price?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ItemUpdateDTO
     */
    quantity?: number | null;
}

/**
 * Check if a given object implements the ItemUpdateDTO interface.
 */
export function instanceOfItemUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ItemUpdateDTOFromJSON(json: any): ItemUpdateDTO {
    return ItemUpdateDTOFromJSONTyped(json, false);
}

export function ItemUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'producer': !exists(json, 'producer') ? undefined : json['producer'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'quantity': !exists(json, 'quantity') ? undefined : json['quantity'],
    };
}

export function ItemUpdateDTOToJSON(value?: ItemUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'producer': value.producer,
        'name': value.name,
        'price': value.price,
        'quantity': value.quantity,
    };
}

