/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { ItemDTOPagedResponse } from './ItemDTOPagedResponse';
import {
    ItemDTOPagedResponseFromJSON,
    ItemDTOPagedResponseFromJSONTyped,
    ItemDTOPagedResponseToJSON,
} from './ItemDTOPagedResponse';

/**
 * 
 * @export
 * @interface ItemDTOPagedResponseRequestResponse
 */
export interface ItemDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {ItemDTOPagedResponse}
     * @memberof ItemDTOPagedResponseRequestResponse
     */
    response?: ItemDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof ItemDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the ItemDTOPagedResponseRequestResponse interface.
 */
export function instanceOfItemDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ItemDTOPagedResponseRequestResponseFromJSON(json: any): ItemDTOPagedResponseRequestResponse {
    return ItemDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function ItemDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : ItemDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function ItemDTOPagedResponseRequestResponseToJSON(value?: ItemDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': ItemDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

