/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemAdminAddDTO
 */
export interface ItemAdminAddDTO {
    /**
     * 
     * @type {string}
     * @memberof ItemAdminAddDTO
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ItemAdminAddDTO
     */
    price?: number;
    /**
     * 
     * @type {number}
     * @memberof ItemAdminAddDTO
     */
    quantity?: number;
    /**
     * 
     * @type {string}
     * @memberof ItemAdminAddDTO
     */
    userId?: string;
}

/**
 * Check if a given object implements the ItemAdminAddDTO interface.
 */
export function instanceOfItemAdminAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ItemAdminAddDTOFromJSON(json: any): ItemAdminAddDTO {
    return ItemAdminAddDTOFromJSONTyped(json, false);
}

export function ItemAdminAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemAdminAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'quantity': !exists(json, 'quantity') ? undefined : json['quantity'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
    };
}

export function ItemAdminAddDTOToJSON(value?: ItemAdminAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'price': value.price,
        'quantity': value.quantity,
        'userId': value.userId,
    };
}

