/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ItemDTO } from './ItemDTO';
import {
    ItemDTOFromJSON,
    ItemDTOFromJSONTyped,
    ItemDTOToJSON,
} from './ItemDTO';

/**
 * 
 * @export
 * @interface ItemDTOPagedResponse
 */
export interface ItemDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof ItemDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof ItemDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof ItemDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<ItemDTO>}
     * @memberof ItemDTOPagedResponse
     */
    data?: Array<ItemDTO> | null;
}

/**
 * Check if a given object implements the ItemDTOPagedResponse interface.
 */
export function instanceOfItemDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ItemDTOPagedResponseFromJSON(json: any): ItemDTOPagedResponse {
    return ItemDTOPagedResponseFromJSONTyped(json, false);
}

export function ItemDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(ItemDTOFromJSON)),
    };
}

export function ItemDTOPagedResponseToJSON(value?: ItemDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(ItemDTOToJSON)),
    };
}

