/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemAddDTO
 */
export interface ItemAddDTO {
    /**
     * 
     * @type {string}
     * @memberof ItemAddDTO
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ItemAddDTO
     */
    price?: number;
    /**
     * 
     * @type {number}
     * @memberof ItemAddDTO
     */
    quantity?: number;
}

/**
 * Check if a given object implements the ItemAddDTO interface.
 */
export function instanceOfItemAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ItemAddDTOFromJSON(json: any): ItemAddDTO {
    return ItemAddDTOFromJSONTyped(json, false);
}

export function ItemAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'quantity': !exists(json, 'quantity') ? undefined : json['quantity'],
    };
}

export function ItemAddDTOToJSON(value?: ItemAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'price': value.price,
        'quantity': value.quantity,
    };
}

