/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemDTO
 */
export interface ItemDTO {
    /**
     * 
     * @type {string}
     * @memberof ItemDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ItemDTO
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ItemDTO
     */
    price?: number;
    /**
     * 
     * @type {number}
     * @memberof ItemDTO
     */
    quantity?: number;
    /**
     * 
     * @type {string}
     * @memberof ItemDTO
     */
    userId?: string;
}

/**
 * Check if a given object implements the ItemDTO interface.
 */
export function instanceOfItemDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ItemDTOFromJSON(json: any): ItemDTO {
    return ItemDTOFromJSONTyped(json, false);
}

export function ItemDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'quantity': !exists(json, 'quantity') ? undefined : json['quantity'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
    };
}

export function ItemDTOToJSON(value?: ItemDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'price': value.price,
        'quantity': value.quantity,
        'userId': value.userId,
    };
}

